### ISSUE TITLE
can't start server.rb

### ISSUE THREAD

**Issue by mattrose** [halorgium/sinatra-oauth#1]
I tried fiddling with the dependency map in config/dependencies.rb, but that just leads me deeper down the rabbit hole on this one.

mattrose@venice:~/sinatra-oauth$ ruby server.rb 
/home/mattrose/local/ruby/lib/ruby/site_ruby/1.8/rubygems.rb:280:in `activate': can't activate extlib (= 0.9.9, runtime) for [], already activated extlib-0.9.14 for ["data_objects-0.9.9", "do_sqlite3-0.9.9"] (Gem::LoadError)
    from /home/mattrose/local/ruby/lib/ruby/site_ruby/1.8/rubygems.rb:68:in`gem'
    from ./config/rubundler.rb:15:in `setup_env'
    from ./config/rubundler.rb:13:in`each'
    from ./config/rubundler.rb:13:in `setup_env'
    from server.rb:3

**Comment by mattrose** [comment]
nm
I just took out all the versions and it now works.

**Comment by halorgium** [comment]
Yer, you should remove all rubundler stuff and replace with bundler ;)

**Comment by halorgium** [comment]
Oh, probably wanna use oauth_provider instead. 
This was a spike to see how things could play out.

**Comment by mattrose** [comment]
Thanks, I'm just trying to wrap my head around the whole oauth procedure right now, and I tend to figure stuff out best by looking at and playing with code.  I'll check out oauth_provider
